services:
  nodejs:
    build:
      context: ./
      dockerfile: Dockerfile
    volumes:
      - ./:/workspaces
      - node_modules_volume:/workspaces/node_modules
      - ${AWS_CA_BUNDLE}:/etc/ssl/certs/ca-bundle.crt
    tty: true
    env_file:
      - .env
    platform: linux/x86_64
volumes:
  node_modules_volume:
